### ISSUE TITLE
Tips for some effects

### ISSUE THREAD

**Issue by p-chan5** [Bundy01/EasyEffects-Presets#1]
Hi. I tried your presets. Bose is my favorite. I also have a [repository](https://github.com/p-chan5/EasyPulse) where I host a couple of these, and well, I wanted to share with you some tips that might help you improve them.

The first thing I noticed was bass distortion on two of them (Custom Bass / Sony). You can see this by migrating the equalizer settings to [LSP Parametric Equalizer x32 Stereo](https://lsp-plug.in/?page=manuals&section=para_equalizer_x32_stereo). Doing this was somewhat difficult due to the decimal numbers followed by the original value plus the non-consecutive number of bands, i.e. `"band1"` > `"band10"`... `"band14"` > `"band2"` This makes me think that you have imported an APO or Graphic EQ preset. It's not bad to do this... but I would recommend reviewing this setting since it's not clear what AutoEq does in the background.

<img src="https://user-images.githubusercontent.com/123143444/223328716-2daa80eb-3e61-4385-b7e3-93dbeda6c800.png" height=150> <img src="https://user-images.githubusercontent.com/123143444/223328729-c7ab6dc1-cd78-40c1-a046-2dbd41c83f08.png" height=150>

The reason I liked the Bose is because it attenuates annoying frequencies (usually the mids), as well as having a much richer bass (but still needs more cleanup).

<img src="https://user-images.githubusercontent.com/123143444/223370346-de075230-29f8-4a18-a625-59f5f45a8ab3.png" height=150>

You can achieve this by using just the Equalizer. Try getting better at this before moving on to more advanced things like the Bass Enhancer.

If you want to avoid saturation, then I recommend replacing the Limiter with the Maximizer; although if you want to keep using it, I have a precise configuration on my [Wiki](https://github.com/p-chan5/EasyPulse/wiki/ARCHIVE#limiter-setting).

**Comment by Bundy01** [comment]
Hi @p-chan5,
thanks for your interest in these presets.

>The first thing I noticed was bass distortion on two of them (Custom Bass / Sony).

What kind of music do you listen to?
Did you notice this distortion when you turned off Bass Enhancer?

>This makes me think that you have imported an APO or Graphic EQ preset.

No, I made the different settings manually.

>If you want to avoid saturation, then I recommend replacing the Limiter with the Maximizer

Thanks for the suggestion, I wanted to stay with the least amount of dependencies but I finally installed `zam-plugins-lv2` to enable Maximizer :)

**Comment by Bundy01** [comment]
#https://github.com/Bundy01/EasyEffects-Presets/commit/c12e0193d8a10242d7154da3ae80abc4820d607c

Can you tell me if this is better?

**Comment by p-chan5** [comment]
> What kind of music do you listen to?

I like to listen to electronic music, lofi, kpop and classical. I have added a couple of Spotify playlists:

[Hardwell's Selection](https://open.spotify.com/playlist/6dBUVyjBcjtrSQ0jEURWmS)
[K-Pop On!](https://open.spotify.com/playlist/37i9dQZF1DX9tPFwDMOaN1)
[Study lofi](https://open.spotify.com/playlist/0vvXsWCC9xrXsKd4FyS8kM)

I use a `sony-mdr-zx110` headphones for it. And you?

> Did you notice this distortion when you turned off Bass Enhancer?

No, it was with the Limiter. It could be avoided by turning on Auto Leveling, but you would have to deal with volume and dynamics issues. That's why I switched to the Maximizer, just add it and the distortion is gone.

You can also explore my [hifi](https://github.com/p-chan5/EasyPulse/blob/main/easyeffects/hifi.json) preset, it's one of the best I've ever made. If you like it you can fork it and add it to yours.

> No, I made the different settings manually.

I understand. Maybe you used `+` and `-` to set the values. It's strange that in the file it shows "threshold": `-6.9999999999999964` and in the interface: `7.0` You can fix it by setting these values ​​using your keyboard.

> Can you tell me if this is better?

Yes, there is no more distortion. Thank you!

**Comment by Bundy01** [comment]
>I use a sony-mdr-zx110 headphones for it. And you?

I use the Logitech Z407 Bluetooth speakers with Reggae Music.

>You can also explore my [hifi](https://github.com/p-chan5/EasyPulse/blob/main/easyeffects/hifi.json) preset, it's one of the best I've ever made. If you like it you can fork it and add it to yours.

I will test it. Thanks for the suggestion to add on this repository :)

>I understand. Maybe you used + and - to set the values. It's strange that in the file it shows "threshold": -6.9999999999999964 and in the interface: 7.0 You can fix it by setting these values ​​using your keyboard.

Indeed, I used the + and - keys. I'll fix it as soon as possible.

Thanks a lot for your help.
